# Get your spec rake tasks working in RSpec 2.0

require 'rspec/core/rake_task'
require 'fileutils'

def browser
  cmd = case RUBY_PLATFORM
  when /darwin/
    "open"
  when /windows/ #fix this, I'm not sure.
    "explorer"
  else
    "x-www-browser"
  end
end


desc 'Default: run specs.'
task :default => :spec

desc "Run specs"
RSpec::Core::RakeTask.new('spec') do |t|
  t.pattern = "./spec/**/*_spec.rb" # don't need this, it's default.
  # Put spec opts in a file named .rspec in root
end

desc "Generate SimpleCov test coverage and open in your browser"
task :coverage do
  FileUtils.rm_rf 'coverage'
  ENV['COVERAGE'] = 'true'
  Rake::Task["spec"].execute
  `#{browser} coverage/index.html`
end
